name: dnetty
description: Dart Netty
version: 1.0.0
author: yanhxcn@gmail.com
homepage: https://github.com/YanhxCN/dnetty

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: